#ifndef __MCA_MENU_H
#define __MCA_MENU_H
// dosshell 3000
// quit 	10;; in applicat.h

#define MAIN_MENU 			0
#define SPECIAL_MENU 		1
#define ABOUT_MENU_ITEM 	2


#define GRAPH				3
#define ROTATE				4
#define HELP 				5

#define NEW  				11
#define CLOSE 				12
#define MYDOSSHELL			13

#define LEFT				22
#define RIGHT				23
#define UP	 				24
#define DOWN   				25
#define NEAR   				26
#define FAR    				27

#define DISTANCE 			28
#define VIEWPOINT			29

#define X_VALUE				31
#define Y_VALUE				32
#define Z_VALUE				33


#endif