//{{NO_DEPENDENCIES}}
//
#define IDC_STATIC                      0
#define IDC_CALCULATE                   508
#define IDC_APPROACH                    509
#define IDC_ELLIPSE                     510

#define IDC_PATHNAME                    1100
#define IDC_TWOSTEP                     1101
#define IDC_ONESTEP                     1102
#define IDC_BROWSE                      1103
#define IDC_SETDEFAULT                  1104
#define IDC_DISPLAY                     1105

#define IDM_EDITDATA                    100
#define IDM_OPENDATA                    110
#define IDM_SAVEDATA                    120
#define IDM_SAVEAS                      125
#define IDM_SHELL                       130
#define IDM_EXIT                        140
#define IDM_CUT                         150
#define IDM_COPY                        160
#define IDM_PASTE                       170
#define IDM_DELETE                      180
#define IDM_FIND                        190
#define IDM_REPLACE                     200
#define IDM_COMPUTE                     204
#define IDM_STOP                        208
#define IDM_VIEW                        212
#define IDM_ERROR                       216
#define IDM_CUTTINGPARAM                218
#define IDM_CONTENTS                    220
#define IDM_INDEX                       230
#define IDM_ABOUT                       240
#define IDM_PRINT                       250


