//
// This header file include type definitions, macro definitions and 
// function declarations.
// These definitions are used to define the original data and cutting 
// data of process piston.
//

// function declarations
BOOL FAR SampleMain( void );
int FAR ErrorBoxProc( PDLGHEADER pDlgHeader, UINT uAction, WORD wID, LONG lParam );
int FAR SampleMainGUIProc( PGUIINFO pGUIInfo, UINT uMsg, WPARAM wParam, LPARAM lParam);
