; tstdisp1.cmd
; November 2, 1996
; This is  command file (or parameter file) for program GPR_DISP
debug                "true"
batch               = "FALSE"
display_all          "true"     ; add = to see parameters for all files
display_none        = "true"    ; remove = to see parameters for 1st file only
next_cmd_filename   = "tstdisp1.cm2"
data_infilename     = "5line07.dzt"
other_format        = "FALSE"
file_header_bytes   = 0
trace_header_bytes  = 0
samples_per_trace   = 0
total_time          = 0
input_datatype      = 0
max_data_val        = 0.0
min_data_val        = 0.0
row_by_row          = "FALSE"
lbl_infilename      = "tstdisp1.lbl"
mrk_infilename      = "5line07.mrk"
xyz_infilename      = "5line07.xyz"
eps_outfilename      "tstdisp1.eps"  ; add = to get EPS file
eps_copies          = 1
channel             = 0
skip_traces         = 0
lock_first_samp     = "true"
first_samp          = 0
last_samp           = 0
num_bad             = 0
bad_traces[]
coord_mode          = 1
first_trace         = 0
last_trace          = 0
first_samp_time     = -3.39
last_samp_time      = "INVALID_VALUE"
horiz_mode          = "T" ;
horiz_start         = "INVALID_VALUE"
horiz_stop          = "INVALID_VALUE"
num_layers          = 0
layer_rdp[]
layer_mode[]
layer_val[]
num_ticks           = 0
tick_tracenum[]
tick_xyz[][]
trace_per_sec       = 0.0
first_trace_time    = "INVALID_VALUE"
last_trace_time     = "INVALID_VALUE"
video_mode          = 0
vx1                 = 10.0
vx2                 = 60.0
vy1                 = 70.0
vy2                 = 90.0
vert_exag           = 1.0
left                = 800
right               = 0
bottom              = 100
top                 = -3.39
range               = 128
background          = "FALSE"
stretch             = 0
local_offset        = 0.0
local_change        = 0.0
brightness          = 0
negative            = "FALSE"
square              = "FALSE"
show_markers        = 20
show_marker_width   = 1
epc_threshold       = 5
epc_contrast        = 255
epc_sign            = 0
epc_gain            = 2.0
portrait            = "FALSE"
use_11x17           = "FALSE"
eps_select_font     = "Times-Roman"
caption_font_size   = 12
caption_left_edge   = 1.25
caption_bottom_edge = 1.00
caption_long_edge   = "FALSE"
caption             = ""
pagenum_font_size   = 12
pagenum_left_edge   = 7.25
pagenum_bottom_edge = 10.00
pagenum             = ""
hpgl_select_font    = "romtrplx"
title               = "mode 1"
laxis_title         = "2-way trav. time (ns)"
laxis_title_offset  = 0.0
laxis_max           
laxis_min           
laxis_tick_show     = "true"
laxis_tick_start    = 100
laxis_tick_int      = -2
laxis_tick_abs_min
laxis_tick_abs_max  = 0
laxis_tick_num      
laxis_tick_ano      = "true"
laxis_tick_skip     = 9
laxis_tick_mid_skip = 4
laxis_ano_left
laxis_ano_right
laxis_title_size    = 0.55
laxis_ano_size      = 0.50
raxis_title         = "Raw Data"
raxis_title_offset  = 0.0
raxis_max           
raxis_min           
raxis_tick_show     = "true"
raxis_tick_start    = 100
raxis_tick_int      = -10
raxis_tick_abs_min
raxis_tick_abs_max
raxis_tick_num      
raxis_tick_ano      = "FALSE"
raxis_tick_skip     = 4
raxis_tick_mid_skip = -1
raxis_ano_left
raxis_ano_right
raxis_title_size    = 0.55
raxis_ano_size      = 0.50
taxis_title
taxis_title_offset  = -3.0
taxis_max
taxis_min
taxis_tick_show     = "FALSE"
taxis_tick_start
taxis_tick_int
taxis_tick_abs_min
taxis_tick_abs_max
taxis_tick_num      = 0
taxis_tick_ano      = "FALSE"
taxis_tick_skip     = 0
taxis_tick_mid_skip = -1
taxis_ano_left
taxis_ano_right
taxis_title_size    = 0.55
taxis_ano_size      = 0.80
baxis_title         = "Trace Number"
baxis_title_offset  = 0.5
baxis_max           
baxis_min           
baxis_tick_show     = "true"
baxis_tick_start    = 800
baxis_tick_int      = -10
baxis_tick_abs_min
baxis_tick_abs_max
baxis_tick_num      
baxis_tick_ano      = "true"
baxis_tick_skip     = 19
baxis_tick_mid_skip = 4
baxis_ano_left
baxis_ano_right
baxis_title_size    = 0.55
baxis_ano_size      = 0.50
