UC add_user(void);
UC del_user(void);
UC chg_usernum(void);
UC chg_userdata(void);
UC acc_tab(void);

UC add_pabx1(void);
UC   del_pabx1(void);
UC   chg_pabx1(void);

UC   add_pos1(void);
UC   del_pos1(void);
UC   chg_pos1(void);

UC   chk_userdata(void);
UC   chk_pbxdata(void);
UC   chk_posdata(void);
UC   chk_spsdata(void);

UC   add_pabx(void);
UC   del_pabx(void);
UC   chg_pabx(void);

UC   add_pos(void);
UC   del_pos(void);
UC   chg_pos(void);

UC   usr_tab(void);

UC   acc_tab(void);

UC   sch_linedata_code(void);
UC   sch_linedata_num(void);
UC   sch_acctele(void);

UC   sps_tab(void);

UC   print_tab1(void);
UC   print_tab2(void);
UC   print_tab3(void);
UC   print_tab4(void);
UC   print_tab5(void);
