#define F1		0x3B00
#define F2		0x3C00
#define F3		0x3D00
#define F4		0x3E00
#define F5		0x3F00
#define F6		0x4000
#define F7		0x4100
#define F8		0x4200
#define F9		0x4300
#define F10		0X4400

#define SPACE		0x3920
#define BACKSPACE	0x0E08
#define TABL		0x0F00
#define TABR		0x0F09
#define ENTER		0x1C0D
#define ESC		0x011B
#define CTRL_BRK	0x1B

#define LEFT		0x4B00
#define RIGHT		0x4D00
#define UP		0x4800
#define DOWN		0x5000

#define HOME		0x4700
#define END		0x4F00
#define PAGEUP		0x4900
#define PAGEDOWN	0x5100
#define INS		0x5200
#define DEL		0x5300

#define PAD_1		0x4F31
#define PAD_2		0x5032
#define PAD_3		0x5133
#define PAD_4		0x4B34
#define PAD_5		0x4C35
#define PAD_6		0x4D36
#define PAD_7		0x4737
#define PAD_8		0x4838
#define PAD_9		0x4939
#define PAD_0		0x5230
#define PAD_D		0x532E

#define KEY_1		0x0231
#define KEY_2		0x0332
#define KEY_3		0x0433
#define KEY_4		0x0534
#define KEY_5		0x0635
#define KEY_6		0x0736
#define KEY_7		0x0837
#define KEY_8		0x0938
#define KEY_9		0x0A39
#define KEY_0		0x0B30

#define ALT_1		0x7800
#define ALT_2		0x7900
#define ALT_3		0x7A00
#define ALT_4		0x7B00
#define ALT_5		0x7C00
#define ALT_6		0x7D00
#define ALT_7		0x7E00
#define ALT_8		0x7F00
#define ALT_9		0x8000
#define ALT_0		0x8100

#define ALT_MINUS	0x8200
#define ALT_PLUS	0x8300
#define MINUS		0x0C2D
#define PLUS		0x0D3D

#define KEY_YES		0x1559
#define KEY_yes		0x1579
#define KEY_NO		0x314e
#define KEY_no		0x316e
